name: Rust Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
    - uses: actions/checkout@v2

    - name: Setup Rust environment
      run: |
        curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        export PATH="$HOME/.cargo/bin:$PATH"

    - name: Install dependencies
      run: cargo build

    - name: Build binary
      run: cargo build --release

    - name: Compress build artifacts
      run: tar -czvf heygpt-{{ matrix.os }}.tgz target/release/heygpt

    - name: Upload compressed artifact
      uses: actions/upload-artifact@v3
      with:
        name: heygpt-{{ matrix.os }}
        path: heygpt-{{ matrix.os }}.tgz
        if-no-files-found: error
    
    - name: Publish to GitHub Release
      if: github.ref == 'refs/heads/main'
      uses: softprops/action-gh-release@v1
      with:
        files: heygpt-{{ matrix.os }}.tgz
        tag_name: v${{ matrix.os }}
        title: Release v${{ matrix.os }}
        body: |
          Changelog:
          - Some change
        prerelease: true
        draft: true